name: Build for 20i Deployment

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro project
        run: npm run build

      - name: Push built files to deployment branch
        run: |
          # Switch to deployment branch
          git checkout --orphan 20i-deploy
          git reset --hard
          
          # Move built files to root
          mv ../dist/* .
          
          # Add essential files
          touch .nojekyll
          
          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          
          # Commit all files
          git add -A
          git commit -m "Build: $(date +'%Y-%m-%d %H:%M:%S')"
          
          # Force push to deployment branch
          git push origin 20i-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}