name: Build and Deploy to 20i

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro project
        run: npm run build

      - name: Create and push deployment branch
        run: |
          # Create orphan branch if it doesn't exist
          if ! git rev-parse --verify 20i-deploy >/dev/null 2>&1; then
            git checkout --orphan 20i-deploy
            git rm -rf .
            touch .nojekyll
            echo "# 20i Deployment Branch" > README.md
            git add .nojekyll README.md
            git commit -m "Initialize 20i deployment branch"
            git push origin 20i-deploy
          fi

          # Switch to deployment branch
          git fetch origin 20i-deploy
          git checkout 20i-deploy
          
          # Remove existing files except .git
          find . -not -path '*/\.git*' -not -name '.git' -delete
          
          # Move built files to root
          cp -r ../dist/* .
          
          # === CRITICAL FOR ASTRO ===
          touch .nojekyll
          echo "User-agent: *" > robots.txt
          echo "Allow: /" >> robots.txt
          # =========================
          
          # Commit and push changes
          git add -A
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git commit -m "Deploy: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin 20i-deploy